/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/ai-worker-claim-meme": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PostAiWorkerClaimMemes"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/meme-tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetMemeTags"];
    put?: never;
    post: operations["PostMemeTags"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/meme-tags/{primaryKey}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetMemeTag"];
    put?: never;
    post?: never;
    delete: operations["DeleteMemeTag"];
    options?: never;
    head?: never;
    patch: operations["PatchMemeTag"];
    trace?: never;
  };
  "/api/memes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetMemes"];
    put?: never;
    post: operations["PostMemes"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/memes/{primaryKey}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetMeme"];
    put?: never;
    post?: never;
    delete: operations["DeleteMeme"];
    options?: never;
    head?: never;
    patch: operations["PatchMeme"];
    trace?: never;
  };
  "/api/memes/{primaryKey}/ai-worker-claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PostMemesAiWorkerClaim"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetTags"];
    put?: never;
    post: operations["PostTags"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tags/{primaryKey}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetTag"];
    put?: never;
    post?: never;
    delete: operations["DeleteTag"];
    options?: never;
    head?: never;
    patch: operations["PatchTag"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ArrayOfNullableMeme: components["schemas"]["Meme"][] | null;
    ArrayOfNullableMemeTag: components["schemas"]["MemeTag"][] | null;
    ArrayOfNullableTag: components["schemas"]["Tag"][] | null;
    ArrayOfString: string[] | null;
    Meme: {
      /** Format: date-time */
      ai_worker_claimed_until?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      deleted_at?: string;
      description?: string;
      /** Format: int64 */
      description_generated?: number;
      description_status?: string;
      filename?: string;
      /** Format: uuid */
      id?: string;
      /** Format: int64 */
      metadata_version?: number;
      mime_type?: string;
      original_name?: string;
      referenced_by_meme_tag_meme_id_objects?:
        components["schemas"]["MemeTag"][] | null;
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      sort_order?: number;
      /** Format: date-time */
      updated_at?: string;
    };
    MemeAiWorkerClaimRequest: {
      /** Format: double */
      timeout_seconds?: number;
      /** Format: date-time */
      until?: string;
    };
    MemeTag: {
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      deleted_at?: string;
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      meme_id?: string;
      meme_id_object?: components["schemas"]["Meme"];
      /** Format: uuid */
      tag_id?: string;
      tag_id_object?: components["schemas"]["Tag"];
      /** Format: date-time */
      updated_at?: string;
    };
    NullableMeme: components["schemas"]["Meme"];
    NullableMemeTag: components["schemas"]["MemeTag"];
    NullableTag: components["schemas"]["Tag"];
    ResponseWithGenericOfMeme: {
      /** Format: int64 */
      count?: number;
      error?: string[] | null;
      /** Format: int64 */
      limit?: number;
      objects?: components["schemas"]["Meme"][] | null;
      /** Format: int64 */
      offset?: number;
      /** Format: int64 */
      status?: number;
      success?: boolean;
      /** Format: int64 */
      total_count?: number;
    };
    ResponseWithGenericOfMemeTag: {
      /** Format: int64 */
      count?: number;
      error?: string[] | null;
      /** Format: int64 */
      limit?: number;
      objects?: components["schemas"]["MemeTag"][] | null;
      /** Format: int64 */
      offset?: number;
      /** Format: int64 */
      status?: number;
      success?: boolean;
      /** Format: int64 */
      total_count?: number;
    };
    ResponseWithGenericOfTag: {
      /** Format: int64 */
      count?: number;
      error?: string[] | null;
      /** Format: int64 */
      limit?: number;
      objects?: components["schemas"]["Tag"][] | null;
      /** Format: int64 */
      offset?: number;
      /** Format: int64 */
      status?: number;
      success?: boolean;
      /** Format: int64 */
      total_count?: number;
    };
    Tag: {
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      deleted_at?: string;
      /** Format: uuid */
      id?: string;
      name?: string;
      referenced_by_meme_tag_tag_id_objects?:
        components["schemas"]["MemeTag"][] | null;
      /** Format: date-time */
      updated_at?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  PostAiWorkerClaimMemes: {
    parameters: {
      query?: {
        /** @description SQL LIMIT operator */
        limit?: number;
        /** @description SQL OFFSET operator */
        offset?: number;
        /**
         * @description Max recursion depth for loading foreign objects; default = 1
         *
         *     (0 = recurse until graph cycle detected, 1 = this object only, 2 = this object + neighbours, 3 = this object + neighbours + their neighbours... etc)
         */
        depth?: number;
        /** @description load the given indirectly related objects, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag__load?: string;
        /** @description SQL = comparison */
        id__eq?: string;
        /** @description SQL != comparison */
        id__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        id__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        id__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        id__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        id__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        id__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        id__notin?: string;
        /** @description SQL @> comparison */
        id__contains?: string;
        /** @description SQL NOT @> comparison */
        id__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        id__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        id__asc?: string;
        /** @description SQL = comparison */
        created_at__eq?: string;
        /** @description SQL != comparison */
        created_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        created_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        created_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        created_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        created_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        created_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        created_at__notin?: string;
        /** @description SQL @> comparison */
        created_at__contains?: string;
        /** @description SQL NOT @> comparison */
        created_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        created_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        created_at__asc?: string;
        /** @description SQL = comparison */
        updated_at__eq?: string;
        /** @description SQL != comparison */
        updated_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        updated_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        updated_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        updated_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        updated_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        updated_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        updated_at__notin?: string;
        /** @description SQL @> comparison */
        updated_at__contains?: string;
        /** @description SQL NOT @> comparison */
        updated_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        updated_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        updated_at__asc?: string;
        /** @description SQL = comparison */
        deleted_at__eq?: string;
        /** @description SQL != comparison */
        deleted_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        deleted_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        deleted_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        deleted_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        deleted_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        deleted_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        deleted_at__notin?: string;
        /** @description SQL @> comparison */
        deleted_at__contains?: string;
        /** @description SQL NOT @> comparison */
        deleted_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        deleted_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        deleted_at__asc?: string;
        /** @description SQL = comparison */
        filename__eq?: string;
        /** @description SQL != comparison */
        filename__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        filename__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        filename__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        filename__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        filename__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        filename__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        filename__notin?: string;
        /** @description SQL @> comparison */
        filename__contains?: string;
        /** @description SQL NOT @> comparison */
        filename__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        filename__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        filename__asc?: string;
        /** @description SQL = comparison */
        original_name__eq?: string;
        /** @description SQL != comparison */
        original_name__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        original_name__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        original_name__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        original_name__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        original_name__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        original_name__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        original_name__notin?: string;
        /** @description SQL @> comparison */
        original_name__contains?: string;
        /** @description SQL NOT @> comparison */
        original_name__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        original_name__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        original_name__asc?: string;
        /** @description SQL = comparison */
        mime_type__eq?: string;
        /** @description SQL != comparison */
        mime_type__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        mime_type__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        mime_type__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        mime_type__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        mime_type__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        mime_type__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        mime_type__notin?: string;
        /** @description SQL @> comparison */
        mime_type__contains?: string;
        /** @description SQL NOT @> comparison */
        mime_type__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        mime_type__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        mime_type__asc?: string;
        /** @description SQL = comparison */
        size__eq?: number;
        /** @description SQL != comparison */
        size__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        size__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        size__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        size__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        size__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        size__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        size__notin?: number;
        /** @description SQL @> comparison */
        size__contains?: number;
        /** @description SQL NOT @> comparison */
        size__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        size__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        size__asc?: string;
        /** @description SQL = comparison */
        description__eq?: string;
        /** @description SQL != comparison */
        description__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        description__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        description__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        description__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        description__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        description__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        description__notin?: string;
        /** @description SQL @> comparison */
        description__contains?: string;
        /** @description SQL NOT @> comparison */
        description__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        description__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        description__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        description__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        description__asc?: string;
        /** @description SQL = comparison */
        description_status__eq?: string;
        /** @description SQL != comparison */
        description_status__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        description_status__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        description_status__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        description_status__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        description_status__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        description_status__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        description_status__notin?: string;
        /** @description SQL @> comparison */
        description_status__contains?: string;
        /** @description SQL NOT @> comparison */
        description_status__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        description_status__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        description_status__asc?: string;
        /** @description SQL = comparison */
        description_generated__eq?: number;
        /** @description SQL != comparison */
        description_generated__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        description_generated__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        description_generated__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        description_generated__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        description_generated__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        description_generated__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        description_generated__notin?: number;
        /** @description SQL @> comparison */
        description_generated__contains?: number;
        /** @description SQL NOT @> comparison */
        description_generated__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        description_generated__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        description_generated__asc?: string;
        /** @description SQL = comparison */
        sort_order__eq?: number;
        /** @description SQL != comparison */
        sort_order__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        sort_order__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        sort_order__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        sort_order__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        sort_order__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        sort_order__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        sort_order__notin?: number;
        /** @description SQL @> comparison */
        sort_order__contains?: number;
        /** @description SQL NOT @> comparison */
        sort_order__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        sort_order__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        sort_order__asc?: string;
        /** @description SQL = comparison */
        metadata_version__eq?: number;
        /** @description SQL != comparison */
        metadata_version__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        metadata_version__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        metadata_version__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        metadata_version__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        metadata_version__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        metadata_version__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        metadata_version__notin?: number;
        /** @description SQL @> comparison */
        metadata_version__contains?: number;
        /** @description SQL NOT @> comparison */
        metadata_version__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        metadata_version__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        metadata_version__asc?: string;
        /** @description SQL = comparison */
        ai_worker_claimed_until__eq?: string;
        /** @description SQL != comparison */
        ai_worker_claimed_until__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        ai_worker_claimed_until__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        ai_worker_claimed_until__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        ai_worker_claimed_until__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        ai_worker_claimed_until__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        ai_worker_claimed_until__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        ai_worker_claimed_until__notin?: string;
        /** @description SQL @> comparison */
        ai_worker_claimed_until__contains?: string;
        /** @description SQL NOT @> comparison */
        ai_worker_claimed_until__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        ai_worker_claimed_until__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        ai_worker_claimed_until__asc?: string;
        /** @description SQL @> comparison */
        referenced_by_meme_tag_meme_id_objects__contains?: unknown;
        /** @description SQL NOT @> comparison */
        referenced_by_meme_tag_meme_id_objects__notcontains?: unknown;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag_meme_id_objects__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag_meme_id_objects__asc?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemeAiWorkerClaimRequest"];
      };
    };
    responses: {
      /** @description PostAiWorkerClaimMemes success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMeme"];
        };
      };
      /** @description PostAiWorkerClaimMemes failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  GetMemeTags: {
    parameters: {
      query?: {
        /** @description SQL LIMIT operator */
        limit?: number;
        /** @description SQL OFFSET operator */
        offset?: number;
        /**
         * @description Max recursion depth for loading foreign objects; default = 1
         *
         *     (0 = recurse until graph cycle detected, 1 = this object only, 2 = this object + neighbours, 3 = this object + neighbours + their neighbours... etc)
         */
        depth?: number;
        /** @description load the given directly related object, value is ignored (presence of key is sufficient) */
        meme__load?: string;
        /** @description load the given directly related object, value is ignored (presence of key is sufficient) */
        tag__load?: string;
        /** @description SQL = comparison */
        id__eq?: string;
        /** @description SQL != comparison */
        id__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        id__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        id__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        id__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        id__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        id__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        id__notin?: string;
        /** @description SQL @> comparison */
        id__contains?: string;
        /** @description SQL NOT @> comparison */
        id__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        id__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        id__asc?: string;
        /** @description SQL = comparison */
        created_at__eq?: string;
        /** @description SQL != comparison */
        created_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        created_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        created_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        created_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        created_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        created_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        created_at__notin?: string;
        /** @description SQL @> comparison */
        created_at__contains?: string;
        /** @description SQL NOT @> comparison */
        created_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        created_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        created_at__asc?: string;
        /** @description SQL = comparison */
        updated_at__eq?: string;
        /** @description SQL != comparison */
        updated_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        updated_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        updated_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        updated_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        updated_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        updated_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        updated_at__notin?: string;
        /** @description SQL @> comparison */
        updated_at__contains?: string;
        /** @description SQL NOT @> comparison */
        updated_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        updated_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        updated_at__asc?: string;
        /** @description SQL = comparison */
        deleted_at__eq?: string;
        /** @description SQL != comparison */
        deleted_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        deleted_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        deleted_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        deleted_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        deleted_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        deleted_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        deleted_at__notin?: string;
        /** @description SQL @> comparison */
        deleted_at__contains?: string;
        /** @description SQL NOT @> comparison */
        deleted_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        deleted_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        deleted_at__asc?: string;
        /** @description SQL = comparison */
        meme_id__eq?: string;
        /** @description SQL != comparison */
        meme_id__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        meme_id__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        meme_id__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        meme_id__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        meme_id__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        meme_id__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        meme_id__notin?: string;
        /** @description SQL @> comparison */
        meme_id__contains?: string;
        /** @description SQL NOT @> comparison */
        meme_id__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        meme_id__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        meme_id__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        meme_id__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        meme_id__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        meme_id__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        meme_id__asc?: string;
        /** @description SQL @> comparison */
        meme_id_object__contains?: unknown;
        /** @description SQL NOT @> comparison */
        meme_id_object__notcontains?: unknown;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        meme_id_object__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        meme_id_object__asc?: string;
        /** @description SQL = comparison */
        tag_id__eq?: string;
        /** @description SQL != comparison */
        tag_id__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        tag_id__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        tag_id__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        tag_id__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        tag_id__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        tag_id__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        tag_id__notin?: string;
        /** @description SQL @> comparison */
        tag_id__contains?: string;
        /** @description SQL NOT @> comparison */
        tag_id__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        tag_id__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        tag_id__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        tag_id__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        tag_id__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        tag_id__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        tag_id__asc?: string;
        /** @description SQL @> comparison */
        tag_id_object__contains?: unknown;
        /** @description SQL NOT @> comparison */
        tag_id_object__notcontains?: unknown;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        tag_id_object__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        tag_id_object__asc?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GetMemeTags success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMemeTag"];
        };
      };
      /** @description GetMemeTags failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  PostMemeTags: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArrayOfNullableMemeTag"];
      };
    };
    responses: {
      /** @description PostMemeTags success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMemeTag"];
        };
      };
      /** @description PostMemeTags failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  GetMemeTag: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GetMemeTag success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMemeTag"];
        };
      };
      /** @description GetMemeTag failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  DeleteMemeTag: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description DeleteMemeTag success */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description DeleteMemeTag failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PatchMemeTag: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemeTag"];
      };
    };
    responses: {
      /** @description PatchMemeTag success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMemeTag"];
        };
      };
      /** @description PatchMemeTag failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  GetMemes: {
    parameters: {
      query?: {
        /** @description SQL LIMIT operator */
        limit?: number;
        /** @description SQL OFFSET operator */
        offset?: number;
        /**
         * @description Max recursion depth for loading foreign objects; default = 1
         *
         *     (0 = recurse until graph cycle detected, 1 = this object only, 2 = this object + neighbours, 3 = this object + neighbours + their neighbours... etc)
         */
        depth?: number;
        /** @description load the given indirectly related objects, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag__load?: string;
        /** @description SQL = comparison */
        id__eq?: string;
        /** @description SQL != comparison */
        id__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        id__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        id__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        id__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        id__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        id__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        id__notin?: string;
        /** @description SQL @> comparison */
        id__contains?: string;
        /** @description SQL NOT @> comparison */
        id__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        id__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        id__asc?: string;
        /** @description SQL = comparison */
        created_at__eq?: string;
        /** @description SQL != comparison */
        created_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        created_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        created_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        created_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        created_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        created_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        created_at__notin?: string;
        /** @description SQL @> comparison */
        created_at__contains?: string;
        /** @description SQL NOT @> comparison */
        created_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        created_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        created_at__asc?: string;
        /** @description SQL = comparison */
        updated_at__eq?: string;
        /** @description SQL != comparison */
        updated_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        updated_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        updated_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        updated_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        updated_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        updated_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        updated_at__notin?: string;
        /** @description SQL @> comparison */
        updated_at__contains?: string;
        /** @description SQL NOT @> comparison */
        updated_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        updated_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        updated_at__asc?: string;
        /** @description SQL = comparison */
        deleted_at__eq?: string;
        /** @description SQL != comparison */
        deleted_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        deleted_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        deleted_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        deleted_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        deleted_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        deleted_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        deleted_at__notin?: string;
        /** @description SQL @> comparison */
        deleted_at__contains?: string;
        /** @description SQL NOT @> comparison */
        deleted_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        deleted_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        deleted_at__asc?: string;
        /** @description SQL = comparison */
        filename__eq?: string;
        /** @description SQL != comparison */
        filename__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        filename__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        filename__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        filename__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        filename__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        filename__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        filename__notin?: string;
        /** @description SQL @> comparison */
        filename__contains?: string;
        /** @description SQL NOT @> comparison */
        filename__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        filename__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        filename__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        filename__asc?: string;
        /** @description SQL = comparison */
        original_name__eq?: string;
        /** @description SQL != comparison */
        original_name__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        original_name__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        original_name__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        original_name__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        original_name__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        original_name__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        original_name__notin?: string;
        /** @description SQL @> comparison */
        original_name__contains?: string;
        /** @description SQL NOT @> comparison */
        original_name__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        original_name__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        original_name__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        original_name__asc?: string;
        /** @description SQL = comparison */
        mime_type__eq?: string;
        /** @description SQL != comparison */
        mime_type__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        mime_type__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        mime_type__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        mime_type__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        mime_type__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        mime_type__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        mime_type__notin?: string;
        /** @description SQL @> comparison */
        mime_type__contains?: string;
        /** @description SQL NOT @> comparison */
        mime_type__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        mime_type__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        mime_type__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        mime_type__asc?: string;
        /** @description SQL = comparison */
        size__eq?: number;
        /** @description SQL != comparison */
        size__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        size__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        size__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        size__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        size__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        size__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        size__notin?: number;
        /** @description SQL @> comparison */
        size__contains?: number;
        /** @description SQL NOT @> comparison */
        size__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        size__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        size__asc?: string;
        /** @description SQL = comparison */
        description__eq?: string;
        /** @description SQL != comparison */
        description__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        description__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        description__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        description__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        description__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        description__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        description__notin?: string;
        /** @description SQL @> comparison */
        description__contains?: string;
        /** @description SQL NOT @> comparison */
        description__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        description__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        description__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        description__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        description__asc?: string;
        /** @description SQL = comparison */
        description_status__eq?: string;
        /** @description SQL != comparison */
        description_status__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        description_status__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        description_status__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        description_status__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        description_status__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        description_status__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        description_status__notin?: string;
        /** @description SQL @> comparison */
        description_status__contains?: string;
        /** @description SQL NOT @> comparison */
        description_status__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        description_status__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        description_status__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        description_status__asc?: string;
        /** @description SQL = comparison */
        description_generated__eq?: number;
        /** @description SQL != comparison */
        description_generated__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        description_generated__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        description_generated__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        description_generated__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        description_generated__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        description_generated__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        description_generated__notin?: number;
        /** @description SQL @> comparison */
        description_generated__contains?: number;
        /** @description SQL NOT @> comparison */
        description_generated__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        description_generated__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        description_generated__asc?: string;
        /** @description SQL = comparison */
        sort_order__eq?: number;
        /** @description SQL != comparison */
        sort_order__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        sort_order__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        sort_order__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        sort_order__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        sort_order__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        sort_order__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        sort_order__notin?: number;
        /** @description SQL @> comparison */
        sort_order__contains?: number;
        /** @description SQL NOT @> comparison */
        sort_order__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        sort_order__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        sort_order__asc?: string;
        /** @description SQL = comparison */
        metadata_version__eq?: number;
        /** @description SQL != comparison */
        metadata_version__ne?: number;
        /** @description SQL > comparison, may not work with all column types */
        metadata_version__gt?: number;
        /** @description SQL >= comparison, may not work with all column types */
        metadata_version__gte?: number;
        /** @description SQL < comparison, may not work with all column types */
        metadata_version__lt?: number;
        /** @description SQL <= comparison, may not work with all column types */
        metadata_version__lte?: number;
        /** @description SQL IN comparison, permits comma-separated values */
        metadata_version__in?: number;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        metadata_version__notin?: number;
        /** @description SQL @> comparison */
        metadata_version__contains?: number;
        /** @description SQL NOT @> comparison */
        metadata_version__notcontains?: number;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        metadata_version__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        metadata_version__asc?: string;
        /** @description SQL = comparison */
        ai_worker_claimed_until__eq?: string;
        /** @description SQL != comparison */
        ai_worker_claimed_until__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        ai_worker_claimed_until__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        ai_worker_claimed_until__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        ai_worker_claimed_until__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        ai_worker_claimed_until__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        ai_worker_claimed_until__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        ai_worker_claimed_until__notin?: string;
        /** @description SQL @> comparison */
        ai_worker_claimed_until__contains?: string;
        /** @description SQL NOT @> comparison */
        ai_worker_claimed_until__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        ai_worker_claimed_until__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        ai_worker_claimed_until__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        ai_worker_claimed_until__asc?: string;
        /** @description SQL @> comparison */
        referenced_by_meme_tag_meme_id_objects__contains?: unknown;
        /** @description SQL NOT @> comparison */
        referenced_by_meme_tag_meme_id_objects__notcontains?: unknown;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag_meme_id_objects__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag_meme_id_objects__asc?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GetMemes success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMeme"];
        };
      };
      /** @description GetMemes failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  PostMemes: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArrayOfNullableMeme"];
      };
    };
    responses: {
      /** @description PostMemes success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMeme"];
        };
      };
      /** @description PostMemes failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  GetMeme: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GetMeme success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMeme"];
        };
      };
      /** @description GetMeme failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  DeleteMeme: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description DeleteMeme success */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description DeleteMeme failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PatchMeme: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Meme"];
      };
    };
    responses: {
      /** @description PatchMeme success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMeme"];
        };
      };
      /** @description PatchMeme failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  PostMemesAiWorkerClaim: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemeAiWorkerClaimRequest"];
      };
    };
    responses: {
      /** @description PostMemesAiWorkerClaim success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfMeme"];
        };
      };
      /** @description PostMemesAiWorkerClaim failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  GetTags: {
    parameters: {
      query?: {
        /** @description SQL LIMIT operator */
        limit?: number;
        /** @description SQL OFFSET operator */
        offset?: number;
        /**
         * @description Max recursion depth for loading foreign objects; default = 1
         *
         *     (0 = recurse until graph cycle detected, 1 = this object only, 2 = this object + neighbours, 3 = this object + neighbours + their neighbours... etc)
         */
        depth?: number;
        /** @description load the given indirectly related objects, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag__load?: string;
        /** @description SQL = comparison */
        id__eq?: string;
        /** @description SQL != comparison */
        id__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        id__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        id__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        id__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        id__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        id__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        id__notin?: string;
        /** @description SQL @> comparison */
        id__contains?: string;
        /** @description SQL NOT @> comparison */
        id__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        id__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        id__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        id__asc?: string;
        /** @description SQL = comparison */
        created_at__eq?: string;
        /** @description SQL != comparison */
        created_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        created_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        created_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        created_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        created_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        created_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        created_at__notin?: string;
        /** @description SQL @> comparison */
        created_at__contains?: string;
        /** @description SQL NOT @> comparison */
        created_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        created_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        created_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        created_at__asc?: string;
        /** @description SQL = comparison */
        updated_at__eq?: string;
        /** @description SQL != comparison */
        updated_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        updated_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        updated_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        updated_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        updated_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        updated_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        updated_at__notin?: string;
        /** @description SQL @> comparison */
        updated_at__contains?: string;
        /** @description SQL NOT @> comparison */
        updated_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        updated_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        updated_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        updated_at__asc?: string;
        /** @description SQL = comparison */
        deleted_at__eq?: string;
        /** @description SQL != comparison */
        deleted_at__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        deleted_at__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        deleted_at__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        deleted_at__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        deleted_at__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        deleted_at__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        deleted_at__notin?: string;
        /** @description SQL @> comparison */
        deleted_at__contains?: string;
        /** @description SQL NOT @> comparison */
        deleted_at__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        deleted_at__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        deleted_at__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        deleted_at__asc?: string;
        /** @description SQL = comparison */
        name__eq?: string;
        /** @description SQL != comparison */
        name__ne?: string;
        /** @description SQL > comparison, may not work with all column types */
        name__gt?: string;
        /** @description SQL >= comparison, may not work with all column types */
        name__gte?: string;
        /** @description SQL < comparison, may not work with all column types */
        name__lt?: string;
        /** @description SQL <= comparison, may not work with all column types */
        name__lte?: string;
        /** @description SQL IN comparison, permits comma-separated values */
        name__in?: string;
        /** @description SQL NOT IN comparison, permits comma-separated values */
        name__notin?: string;
        /** @description SQL @> comparison */
        name__contains?: string;
        /** @description SQL NOT @> comparison */
        name__notcontains?: string;
        /** @description SQL LIKE comparison, value is implicitly prefixed and suffixed with % */
        name__like?: string;
        /** @description SQL NOT LIKE comparison, value is implicitly prefixed and suffixed with % */
        name__notlike?: string;
        /** @description SQL ILIKE comparison, value is implicitly prefixed and suffixed with % */
        name__ilike?: string;
        /** @description SQL NOT ILIKE comparison, value is implicitly prefixed and suffixed with % */
        name__notilike?: string;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        name__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        name__asc?: string;
        /** @description SQL @> comparison */
        referenced_by_meme_tag_tag_id_objects__contains?: unknown;
        /** @description SQL NOT @> comparison */
        referenced_by_meme_tag_tag_id_objects__notcontains?: unknown;
        /** @description SQL ORDER BY _ DESC clause, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag_tag_id_objects__desc?: string;
        /** @description SQL ORDER BY _ ASC clause, value is ignored (presence of key is sufficient) */
        referenced_by_meme_tag_tag_id_objects__asc?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GetTags success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfTag"];
        };
      };
      /** @description GetTags failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  PostTags: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArrayOfNullableTag"];
      };
    };
    responses: {
      /** @description PostTags success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfTag"];
        };
      };
      /** @description PostTags failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  GetTag: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GetTag success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfTag"];
        };
      };
      /** @description GetTag failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
  DeleteTag: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description DeleteTag success */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description DeleteTag failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PatchTag: {
    parameters: {
      query?: {
        /** @description Query parameter depth */
        depth?: number;
      };
      header?: never;
      path: {
        /** @description Path parameter primaryKey */
        primaryKey: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Tag"];
      };
    };
    responses: {
      /** @description PatchTag success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseWithGenericOfTag"];
        };
      };
      /** @description PatchTag failure */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string[];
            /** Format: int32 */
            status: number;
            success: boolean;
          };
        };
      };
    };
  };
}
