/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the Meme type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Meme{}

// Meme struct for Meme
type Meme struct {
	AiWorkerClaimedUntil *time.Time `json:"ai_worker_claimed_until,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	Description *string `json:"description,omitempty"`
	DescriptionGenerated *int64 `json:"description_generated,omitempty"`
	DescriptionStatus *string `json:"description_status,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Id *string `json:"id,omitempty"`
	MetadataVersion *int64 `json:"metadata_version,omitempty"`
	MimeType *string `json:"mime_type,omitempty"`
	OriginalName *string `json:"original_name,omitempty"`
	ReferencedByMemeTagMemeIdObjects []MemeTag `json:"referenced_by_meme_tag_meme_id_objects,omitempty"`
	Size *int64 `json:"size,omitempty"`
	SortOrder *int64 `json:"sort_order,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewMeme instantiates a new Meme object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeme() *Meme {
	this := Meme{}
	return &this
}

// NewMemeWithDefaults instantiates a new Meme object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemeWithDefaults() *Meme {
	this := Meme{}
	return &this
}

// GetAiWorkerClaimedUntil returns the AiWorkerClaimedUntil field value if set, zero value otherwise.
func (o *Meme) GetAiWorkerClaimedUntil() time.Time {
	if o == nil || IsNil(o.AiWorkerClaimedUntil) {
		var ret time.Time
		return ret
	}
	return *o.AiWorkerClaimedUntil
}

// GetAiWorkerClaimedUntilOk returns a tuple with the AiWorkerClaimedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetAiWorkerClaimedUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AiWorkerClaimedUntil) {
		return nil, false
	}
	return o.AiWorkerClaimedUntil, true
}

// HasAiWorkerClaimedUntil returns a boolean if a field has been set.
func (o *Meme) HasAiWorkerClaimedUntil() bool {
	if o != nil && !IsNil(o.AiWorkerClaimedUntil) {
		return true
	}

	return false
}

// SetAiWorkerClaimedUntil gets a reference to the given time.Time and assigns it to the AiWorkerClaimedUntil field.
func (o *Meme) SetAiWorkerClaimedUntil(v time.Time) {
	o.AiWorkerClaimedUntil = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Meme) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Meme) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Meme) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *Meme) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *Meme) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *Meme) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Meme) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Meme) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Meme) SetDescription(v string) {
	o.Description = &v
}

// GetDescriptionGenerated returns the DescriptionGenerated field value if set, zero value otherwise.
func (o *Meme) GetDescriptionGenerated() int64 {
	if o == nil || IsNil(o.DescriptionGenerated) {
		var ret int64
		return ret
	}
	return *o.DescriptionGenerated
}

// GetDescriptionGeneratedOk returns a tuple with the DescriptionGenerated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetDescriptionGeneratedOk() (*int64, bool) {
	if o == nil || IsNil(o.DescriptionGenerated) {
		return nil, false
	}
	return o.DescriptionGenerated, true
}

// HasDescriptionGenerated returns a boolean if a field has been set.
func (o *Meme) HasDescriptionGenerated() bool {
	if o != nil && !IsNil(o.DescriptionGenerated) {
		return true
	}

	return false
}

// SetDescriptionGenerated gets a reference to the given int64 and assigns it to the DescriptionGenerated field.
func (o *Meme) SetDescriptionGenerated(v int64) {
	o.DescriptionGenerated = &v
}

// GetDescriptionStatus returns the DescriptionStatus field value if set, zero value otherwise.
func (o *Meme) GetDescriptionStatus() string {
	if o == nil || IsNil(o.DescriptionStatus) {
		var ret string
		return ret
	}
	return *o.DescriptionStatus
}

// GetDescriptionStatusOk returns a tuple with the DescriptionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetDescriptionStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DescriptionStatus) {
		return nil, false
	}
	return o.DescriptionStatus, true
}

// HasDescriptionStatus returns a boolean if a field has been set.
func (o *Meme) HasDescriptionStatus() bool {
	if o != nil && !IsNil(o.DescriptionStatus) {
		return true
	}

	return false
}

// SetDescriptionStatus gets a reference to the given string and assigns it to the DescriptionStatus field.
func (o *Meme) SetDescriptionStatus(v string) {
	o.DescriptionStatus = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *Meme) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *Meme) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *Meme) SetFilename(v string) {
	o.Filename = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Meme) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Meme) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Meme) SetId(v string) {
	o.Id = &v
}

// GetMetadataVersion returns the MetadataVersion field value if set, zero value otherwise.
func (o *Meme) GetMetadataVersion() int64 {
	if o == nil || IsNil(o.MetadataVersion) {
		var ret int64
		return ret
	}
	return *o.MetadataVersion
}

// GetMetadataVersionOk returns a tuple with the MetadataVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetMetadataVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.MetadataVersion) {
		return nil, false
	}
	return o.MetadataVersion, true
}

// HasMetadataVersion returns a boolean if a field has been set.
func (o *Meme) HasMetadataVersion() bool {
	if o != nil && !IsNil(o.MetadataVersion) {
		return true
	}

	return false
}

// SetMetadataVersion gets a reference to the given int64 and assigns it to the MetadataVersion field.
func (o *Meme) SetMetadataVersion(v int64) {
	o.MetadataVersion = &v
}

// GetMimeType returns the MimeType field value if set, zero value otherwise.
func (o *Meme) GetMimeType() string {
	if o == nil || IsNil(o.MimeType) {
		var ret string
		return ret
	}
	return *o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetMimeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MimeType) {
		return nil, false
	}
	return o.MimeType, true
}

// HasMimeType returns a boolean if a field has been set.
func (o *Meme) HasMimeType() bool {
	if o != nil && !IsNil(o.MimeType) {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given string and assigns it to the MimeType field.
func (o *Meme) SetMimeType(v string) {
	o.MimeType = &v
}

// GetOriginalName returns the OriginalName field value if set, zero value otherwise.
func (o *Meme) GetOriginalName() string {
	if o == nil || IsNil(o.OriginalName) {
		var ret string
		return ret
	}
	return *o.OriginalName
}

// GetOriginalNameOk returns a tuple with the OriginalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetOriginalNameOk() (*string, bool) {
	if o == nil || IsNil(o.OriginalName) {
		return nil, false
	}
	return o.OriginalName, true
}

// HasOriginalName returns a boolean if a field has been set.
func (o *Meme) HasOriginalName() bool {
	if o != nil && !IsNil(o.OriginalName) {
		return true
	}

	return false
}

// SetOriginalName gets a reference to the given string and assigns it to the OriginalName field.
func (o *Meme) SetOriginalName(v string) {
	o.OriginalName = &v
}

// GetReferencedByMemeTagMemeIdObjects returns the ReferencedByMemeTagMemeIdObjects field value if set, zero value otherwise.
func (o *Meme) GetReferencedByMemeTagMemeIdObjects() []MemeTag {
	if o == nil || IsNil(o.ReferencedByMemeTagMemeIdObjects) {
		var ret []MemeTag
		return ret
	}
	return o.ReferencedByMemeTagMemeIdObjects
}

// GetReferencedByMemeTagMemeIdObjectsOk returns a tuple with the ReferencedByMemeTagMemeIdObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetReferencedByMemeTagMemeIdObjectsOk() ([]MemeTag, bool) {
	if o == nil || IsNil(o.ReferencedByMemeTagMemeIdObjects) {
		return nil, false
	}
	return o.ReferencedByMemeTagMemeIdObjects, true
}

// HasReferencedByMemeTagMemeIdObjects returns a boolean if a field has been set.
func (o *Meme) HasReferencedByMemeTagMemeIdObjects() bool {
	if o != nil && !IsNil(o.ReferencedByMemeTagMemeIdObjects) {
		return true
	}

	return false
}

// SetReferencedByMemeTagMemeIdObjects gets a reference to the given []MemeTag and assigns it to the ReferencedByMemeTagMemeIdObjects field.
func (o *Meme) SetReferencedByMemeTagMemeIdObjects(v []MemeTag) {
	o.ReferencedByMemeTagMemeIdObjects = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Meme) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Meme) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *Meme) SetSize(v int64) {
	o.Size = &v
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise.
func (o *Meme) GetSortOrder() int64 {
	if o == nil || IsNil(o.SortOrder) {
		var ret int64
		return ret
	}
	return *o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetSortOrderOk() (*int64, bool) {
	if o == nil || IsNil(o.SortOrder) {
		return nil, false
	}
	return o.SortOrder, true
}

// HasSortOrder returns a boolean if a field has been set.
func (o *Meme) HasSortOrder() bool {
	if o != nil && !IsNil(o.SortOrder) {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given int64 and assigns it to the SortOrder field.
func (o *Meme) SetSortOrder(v int64) {
	o.SortOrder = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Meme) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Meme) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Meme) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Meme) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Meme) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Meme) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AiWorkerClaimedUntil) {
		toSerialize["ai_worker_claimed_until"] = o.AiWorkerClaimedUntil
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DescriptionGenerated) {
		toSerialize["description_generated"] = o.DescriptionGenerated
	}
	if !IsNil(o.DescriptionStatus) {
		toSerialize["description_status"] = o.DescriptionStatus
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MetadataVersion) {
		toSerialize["metadata_version"] = o.MetadataVersion
	}
	if !IsNil(o.MimeType) {
		toSerialize["mime_type"] = o.MimeType
	}
	if !IsNil(o.OriginalName) {
		toSerialize["original_name"] = o.OriginalName
	}
	if !IsNil(o.ReferencedByMemeTagMemeIdObjects) {
		toSerialize["referenced_by_meme_tag_meme_id_objects"] = o.ReferencedByMemeTagMemeIdObjects
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.SortOrder) {
		toSerialize["sort_order"] = o.SortOrder
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableMeme struct {
	value *Meme
	isSet bool
}

func (v NullableMeme) Get() *Meme {
	return v.value
}

func (v *NullableMeme) Set(val *Meme) {
	v.value = val
	v.isSet = true
}

func (v NullableMeme) IsSet() bool {
	return v.isSet
}

func (v *NullableMeme) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeme(val *Meme) *NullableMeme {
	return &NullableMeme{value: val, isSet: true}
}

func (v NullableMeme) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeme) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


