/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the MemeTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemeTag{}

// MemeTag struct for MemeTag
type MemeTag struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	Id *string `json:"id,omitempty"`
	MemeId *string `json:"meme_id,omitempty"`
	MemeIdObject *Meme `json:"meme_id_object,omitempty"`
	TagId *string `json:"tag_id,omitempty"`
	TagIdObject *Tag `json:"tag_id_object,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewMemeTag instantiates a new MemeTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemeTag() *MemeTag {
	this := MemeTag{}
	return &this
}

// NewMemeTagWithDefaults instantiates a new MemeTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemeTagWithDefaults() *MemeTag {
	this := MemeTag{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *MemeTag) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *MemeTag) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *MemeTag) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *MemeTag) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *MemeTag) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *MemeTag) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MemeTag) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MemeTag) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MemeTag) SetId(v string) {
	o.Id = &v
}

// GetMemeId returns the MemeId field value if set, zero value otherwise.
func (o *MemeTag) GetMemeId() string {
	if o == nil || IsNil(o.MemeId) {
		var ret string
		return ret
	}
	return *o.MemeId
}

// GetMemeIdOk returns a tuple with the MemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetMemeIdOk() (*string, bool) {
	if o == nil || IsNil(o.MemeId) {
		return nil, false
	}
	return o.MemeId, true
}

// HasMemeId returns a boolean if a field has been set.
func (o *MemeTag) HasMemeId() bool {
	if o != nil && !IsNil(o.MemeId) {
		return true
	}

	return false
}

// SetMemeId gets a reference to the given string and assigns it to the MemeId field.
func (o *MemeTag) SetMemeId(v string) {
	o.MemeId = &v
}

// GetMemeIdObject returns the MemeIdObject field value if set, zero value otherwise.
func (o *MemeTag) GetMemeIdObject() Meme {
	if o == nil || IsNil(o.MemeIdObject) {
		var ret Meme
		return ret
	}
	return *o.MemeIdObject
}

// GetMemeIdObjectOk returns a tuple with the MemeIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetMemeIdObjectOk() (*Meme, bool) {
	if o == nil || IsNil(o.MemeIdObject) {
		return nil, false
	}
	return o.MemeIdObject, true
}

// HasMemeIdObject returns a boolean if a field has been set.
func (o *MemeTag) HasMemeIdObject() bool {
	if o != nil && !IsNil(o.MemeIdObject) {
		return true
	}

	return false
}

// SetMemeIdObject gets a reference to the given Meme and assigns it to the MemeIdObject field.
func (o *MemeTag) SetMemeIdObject(v Meme) {
	o.MemeIdObject = &v
}

// GetTagId returns the TagId field value if set, zero value otherwise.
func (o *MemeTag) GetTagId() string {
	if o == nil || IsNil(o.TagId) {
		var ret string
		return ret
	}
	return *o.TagId
}

// GetTagIdOk returns a tuple with the TagId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetTagIdOk() (*string, bool) {
	if o == nil || IsNil(o.TagId) {
		return nil, false
	}
	return o.TagId, true
}

// HasTagId returns a boolean if a field has been set.
func (o *MemeTag) HasTagId() bool {
	if o != nil && !IsNil(o.TagId) {
		return true
	}

	return false
}

// SetTagId gets a reference to the given string and assigns it to the TagId field.
func (o *MemeTag) SetTagId(v string) {
	o.TagId = &v
}

// GetTagIdObject returns the TagIdObject field value if set, zero value otherwise.
func (o *MemeTag) GetTagIdObject() Tag {
	if o == nil || IsNil(o.TagIdObject) {
		var ret Tag
		return ret
	}
	return *o.TagIdObject
}

// GetTagIdObjectOk returns a tuple with the TagIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetTagIdObjectOk() (*Tag, bool) {
	if o == nil || IsNil(o.TagIdObject) {
		return nil, false
	}
	return o.TagIdObject, true
}

// HasTagIdObject returns a boolean if a field has been set.
func (o *MemeTag) HasTagIdObject() bool {
	if o != nil && !IsNil(o.TagIdObject) {
		return true
	}

	return false
}

// SetTagIdObject gets a reference to the given Tag and assigns it to the TagIdObject field.
func (o *MemeTag) SetTagIdObject(v Tag) {
	o.TagIdObject = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *MemeTag) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeTag) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MemeTag) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *MemeTag) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o MemeTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemeTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MemeId) {
		toSerialize["meme_id"] = o.MemeId
	}
	if !IsNil(o.MemeIdObject) {
		toSerialize["meme_id_object"] = o.MemeIdObject
	}
	if !IsNil(o.TagId) {
		toSerialize["tag_id"] = o.TagId
	}
	if !IsNil(o.TagIdObject) {
		toSerialize["tag_id_object"] = o.TagIdObject
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableMemeTag struct {
	value *MemeTag
	isSet bool
}

func (v NullableMemeTag) Get() *MemeTag {
	return v.value
}

func (v *NullableMemeTag) Set(val *MemeTag) {
	v.value = val
	v.isSet = true
}

func (v NullableMemeTag) IsSet() bool {
	return v.isSet
}

func (v *NullableMemeTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemeTag(val *MemeTag) *NullableMemeTag {
	return &NullableMemeTag{value: val, isSet: true}
}

func (v NullableMemeTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemeTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


