/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the MemeAiWorkerClaimRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemeAiWorkerClaimRequest{}

// MemeAiWorkerClaimRequest struct for MemeAiWorkerClaimRequest
type MemeAiWorkerClaimRequest struct {
	TimeoutSeconds *float64 `json:"timeout_seconds,omitempty"`
	Until *time.Time `json:"until,omitempty"`
}

// NewMemeAiWorkerClaimRequest instantiates a new MemeAiWorkerClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemeAiWorkerClaimRequest() *MemeAiWorkerClaimRequest {
	this := MemeAiWorkerClaimRequest{}
	return &this
}

// NewMemeAiWorkerClaimRequestWithDefaults instantiates a new MemeAiWorkerClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemeAiWorkerClaimRequestWithDefaults() *MemeAiWorkerClaimRequest {
	this := MemeAiWorkerClaimRequest{}
	return &this
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *MemeAiWorkerClaimRequest) GetTimeoutSeconds() float64 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret float64
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeAiWorkerClaimRequest) GetTimeoutSecondsOk() (*float64, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *MemeAiWorkerClaimRequest) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given float64 and assigns it to the TimeoutSeconds field.
func (o *MemeAiWorkerClaimRequest) SetTimeoutSeconds(v float64) {
	o.TimeoutSeconds = &v
}

// GetUntil returns the Until field value if set, zero value otherwise.
func (o *MemeAiWorkerClaimRequest) GetUntil() time.Time {
	if o == nil || IsNil(o.Until) {
		var ret time.Time
		return ret
	}
	return *o.Until
}

// GetUntilOk returns a tuple with the Until field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemeAiWorkerClaimRequest) GetUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Until) {
		return nil, false
	}
	return o.Until, true
}

// HasUntil returns a boolean if a field has been set.
func (o *MemeAiWorkerClaimRequest) HasUntil() bool {
	if o != nil && !IsNil(o.Until) {
		return true
	}

	return false
}

// SetUntil gets a reference to the given time.Time and assigns it to the Until field.
func (o *MemeAiWorkerClaimRequest) SetUntil(v time.Time) {
	o.Until = &v
}

func (o MemeAiWorkerClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemeAiWorkerClaimRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	if !IsNil(o.Until) {
		toSerialize["until"] = o.Until
	}
	return toSerialize, nil
}

type NullableMemeAiWorkerClaimRequest struct {
	value *MemeAiWorkerClaimRequest
	isSet bool
}

func (v NullableMemeAiWorkerClaimRequest) Get() *MemeAiWorkerClaimRequest {
	return v.value
}

func (v *NullableMemeAiWorkerClaimRequest) Set(val *MemeAiWorkerClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMemeAiWorkerClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMemeAiWorkerClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemeAiWorkerClaimRequest(val *MemeAiWorkerClaimRequest) *NullableMemeAiWorkerClaimRequest {
	return &NullableMemeAiWorkerClaimRequest{value: val, isSet: true}
}

func (v NullableMemeAiWorkerClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemeAiWorkerClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


